
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/RCA_8 

module RCA_8(x_in, y_in, Cin, sum, Cout );

input x_in[0],x_in[1],x_in[2],x_in[3],x_in[4],x_in[5],x_in[6],x_in[7],y_in[0],y_in[1],y_in[2],y_in[3],y_in[4],y_in[5],y_in[6],y_in[7],Cin;
output sum[0],sum[1],sum[2],sum[3],sum[4],sum[5],sum[6],sum[7],Cout;

wire [7:0] x_in, y_in;
wire Cin;
wire [7:0] sum;
wire Cout;
wire [8:0] CO1;
wire inst0_FA_g, inst0_FA_n_4, inst0_FA_n_5, inst1_FA_g, inst1_FA_n_4, inst1_FA_n_5, inst2_FA_g, inst2_FA_n_4 ;
wire inst2_FA_n_5, inst3_FA_g, inst3_FA_n_4, inst3_FA_n_5, inst4_FA_g, inst4_FA_n_4, inst4_FA_n_5, inst5_FA_g ;
wire inst5_FA_n_4, inst5_FA_n_5, inst6_FA_g, inst6_FA_n_4, inst6_FA_n_5, inst7_FA_g, inst7_FA_n_4, inst7_FA_n_5 ;

xor inst4_FA_g1 (inst4_FA_g, x_in[4], y_in[4]);
xor inst4_FA_g2 (sum[4], inst4_FA_g, CO1[4]);
and inst4_FA_g3 (inst4_FA_n_4, x_in[4], y_in[4]);
and inst4_FA_g4 (inst4_FA_n_5, inst4_FA_g, CO1[4]);
or inst4_FA_g5 (CO1[5], inst4_FA_n_4, inst4_FA_n_5);
xor inst0_FA_g1 (inst0_FA_g, x_in[0], y_in[0]);
xor inst0_FA_g2 (sum[0], inst0_FA_g, Cin);
and inst0_FA_g3 (inst0_FA_n_4, x_in[0], y_in[0]);
and inst0_FA_g4 (inst0_FA_n_5, inst0_FA_g, Cin);
or inst0_FA_g5 (CO1[1], inst0_FA_n_4, inst0_FA_n_5);
xor inst5_FA_g1 (inst5_FA_g, x_in[5], y_in[5]);
xor inst5_FA_g2 (sum[5], inst5_FA_g, CO1[5]);
and inst5_FA_g3 (inst5_FA_n_4, x_in[5], y_in[5]);
and inst5_FA_g4 (inst5_FA_n_5, inst5_FA_g, CO1[5]);
or inst5_FA_g5 (CO1[6], inst5_FA_n_4, inst5_FA_n_5);
xor inst1_FA_g1 (inst1_FA_g, x_in[1], y_in[1]);
xor inst1_FA_g2 (sum[1], inst1_FA_g, CO1[1]);
and inst1_FA_g3 (inst1_FA_n_4, x_in[1], y_in[1]);
and inst1_FA_g4 (inst1_FA_n_5, inst1_FA_g, CO1[1]);
or inst1_FA_g5 (CO1[2], inst1_FA_n_4, inst1_FA_n_5);
xor inst6_FA_g1 (inst6_FA_g, x_in[6], y_in[6]);
xor inst6_FA_g2 (sum[6], inst6_FA_g, CO1[6]);
and inst6_FA_g3 (inst6_FA_n_4, x_in[6], y_in[6]);
and inst6_FA_g4 (inst6_FA_n_5, inst6_FA_g, CO1[6]);
or inst6_FA_g5 (CO1[7], inst6_FA_n_4, inst6_FA_n_5);
xor inst2_FA_g1 (inst2_FA_g, x_in[2], y_in[2]);
xor inst2_FA_g2 (sum[2], inst2_FA_g, CO1[2]);
and inst2_FA_g3 (inst2_FA_n_4, x_in[2], y_in[2]);
and inst2_FA_g4 (inst2_FA_n_5, inst2_FA_g, CO1[2]);
or inst2_FA_g5 (CO1[3], inst2_FA_n_4, inst2_FA_n_5);
xor inst7_FA_g1 (inst7_FA_g, x_in[7], y_in[7]);
xor inst7_FA_g2 (sum[7], inst7_FA_g, CO1[7]);
and inst7_FA_g3 (inst7_FA_n_4, x_in[7], y_in[7]);
and inst7_FA_g4 (inst7_FA_n_5, inst7_FA_g, CO1[7]);
or inst7_FA_g5 (Cout, inst7_FA_n_4, inst7_FA_n_5);
xor inst3_FA_g1 (inst3_FA_g, x_in[3], y_in[3]);
xor inst3_FA_g2 (sum[3], inst3_FA_g, CO1[3]);
and inst3_FA_g3 (inst3_FA_n_4, x_in[3], y_in[3]);
and inst3_FA_g4 (inst3_FA_n_5, inst3_FA_g, CO1[3]);
or inst3_FA_g5 (CO1[4], inst3_FA_n_4, inst3_FA_n_5);

endmodule

